version: "3.8"
services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_BD}
    ports:
      - "${DB_PORT}:5432"
  web:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DISABLE_WATCHPACK=true
    volumes:
      - .:/app
      - /app/node_modules
