name: 'clone-tabnews'
services:
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:16.0-alpine'
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data: